from Tabular import Tabular
from IncrementalTabular import IncrementalTabular
from IndependentDiscretization import IndependentDiscretization
from IndependentDiscretizationCompactBinary import IndependentDiscretizationCompactBinary
from RBF import RBF
from iFDD import iFDD
from Fourier import Fourier
from BEBF import BEBF
from OMPTD import OMPTD
from tiles import TileCoding
